[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["mnemonikr"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/mnemonikr/sla-fuzz"

[patch.crates-io]
libsla-sys = { path = "../libsla-sys/" }
