[package]
name = "sla-fuzz"
version = "1.0.0"
authors.workspace = true
edition.workspace = true 
license.workspace = true
repository.workspace = true

[dependencies]
libfuzzer-sys = "0.4"
libsla = { version = "0.4.3", features = ["fuzzing"] }
